/**************************************************************************
   Desenvolvido por: Felipe Augusto da Silva;
   Data de Criação: 23/10/2013;
   Funcionalidade: Oz Constantes Integração.
**************************************************************************/
public class OzConstantesIntegracao {

	public static final String METHOD_POST = 'POST';
	public static final String METHOD_GET = 'GET';

}